import React from 'react';
import { Accordion, Carousel, Col, Container, Row } from 'react-bootstrap';
import './Blog.css'
const Blog = () => {
  return (
    <div className='banner'>
    <Container>
  <Row>
    <Col sm={12} md={6} lg={6}>
    <Accordion className='mt-5'>
  <Accordion.Item eventKey="0" className='mb-4'>
    <Accordion.Header>Difference between authorization and authentication.</Accordion.Header>
    <Accordion.Body>
     <h2>Authentication:</h2>
     <ul>
         <li>Authentication is the checking of identity to provide the access to te system</li>
         <li>In authentication the user will be verified</li>
         <li>Authentication is done before authorization</li>
     </ul>
     <br></br>
     <h2>Authorization:</h2>
     <ul>
         <li>Authorization is what users can and cannot access.</li>
         <li>Authorization verifies whether the access of users are allowed through terms and conditions.</li>
         <li>It is done after successful authentication</li>
     </ul>
    </Accordion.Body>
  </Accordion.Item>
  <Accordion.Item eventKey="1" className='mb-4'>
    <Accordion.Header>Why we are using firebase? What other options do we have to implement authentication?</Accordion.Header>
    <Accordion.Body>
     <p>The main reasons behind using firebase is , firebase provides plenty of features like: Firebase database, Firebase Authentication, Firebase cloud Storage.We can use  React firebase-hooks which makes authentication much easier and cleaner
<br></br>
<br></br>

<b>Firebase database:</b> It is used to store users data and details.
<br></br>
<b>Firebase Authentication:</b> We can use the authentication by firebase quite easily.
<br></br>
<b>Firebase cloud Storage:</b> It is used to store the contents like profile pictures , messages etc which are generated by the users.
</p>
<br></br>

<p>Other alternative of firebase authentication can be:
</p>
<ui>
    <li>auth0.com
 </li>
    <li>
okta.com
</li>
    <li>
Keycloak 
</li>
</ui>
    </Accordion.Body>
  </Accordion.Item>
  <Accordion.Item eventKey="2">
    <Accordion.Header>What other services does firebase provide other than authentication?</Accordion.Header>
    <Accordion.Body>
        <p>The other services which is provided by firebase are: </p>
    <ui>
    <li>
    Cloud Messaging
 </li>
    <li>
    Cloud Firestore
</li>
    <li>
    Cloud Functions 
</li>
    <li>
    Hosting 
</li>
    <li>
    Google Analytics 
</li>
    <li>
    Remote Configuration 
</li>
    <li>
    Predictions 
</li>
    <li>
    Realtime Database 
</li>
</ui>
    </Accordion.Body>
  </Accordion.Item>
</Accordion>
</Col>
    <Col sm={12} md={6} lg={6}>
      <img src='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTj4HVbCmXTraw04GF-BQHGwuH5pOFVytLShDCKyvX4ehp6dFm3DnJErbd9RUs7P5aOYs8&usqp=CAU' className='img-fluid w-100 mt-2'></img>
    </Col>
  </Row>
 
</Container>
    </div>
  );
};

export default Blog;
